FROM python:3.9
MAINTAINER HUSKI3

# Source
COPY /src .
# Autogenerated components from the build script
COPY /artifacts .

RUN python3.9 -m pip install rich
RUN python3.9 tli.py --install-full

CMD ["python3.9 tli.py"]